build:
  value: 2.0

loans:
  description: "This is a Loan MS which is a part of the Bank Appn: Prod"
  owner:
    name: "Riyasshri"
    email: "riya@gmail.com"
  mobile:
    - 1234567890
    - 2345678901